name: 🧠 Metrics Dashboard

on:
  schedule:
    - cron: "0 0 * * *"  # mỗi ngày lúc 0:00 UTC (7h sáng VN)
  workflow_dispatch:

jobs:
  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nahvine
          config_timezone: Asia/Ho_Chi_Minh
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: false

  topics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.topics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nahvine
          config_timezone: Asia/Ho_Chi_Minh
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nahvine
          config_timezone: Asia/Ho_Chi_Minh
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0

  # 🎯 Tổng hợp các plugin vào 1 file metrics.svg duy nhất
  full_dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Generate full metrics dashboard
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nahvine
          config_timezone: Asia/Ho_Chi_Minh
          filename: metrics.svg

          base: header, activity, repositories

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_trim: false

          plugin_topics: yes
          plugin_topics_limit: 15

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0

          committer_branch: main
          committer_message: "📊 Update full metrics dashboard"
