name: GitHub Metrics

on:
  # Cập nhật tự động mỗi ngày
  schedule: 
    - cron: "0 0 * * *"
  # Cho phép cập nhật thủ công
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Nahvine
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Ho_Chi_Minh
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_traffic: yes
          plugin_repositories: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 5
